### PR TITLE
Fix clash issue 1686

### PR DESCRIPTION
**Pull request by christiaanb**

### CODE REVIEW

**Comment by gergoerdi** [comment]
```
/home/cactus/prog/clash/bugs/clash-issue-1686/Setup.hs:21:0: error:
     error: missing binary operator before token "("
       21 | #if MIN_VERSION_ghc(8,10,0)
          | 
   |
21 | #if MIN_VERSION_ghc(8,10,0)
   | ^

/home/cactus/prog/clash/bugs/clash-issue-1686/Setup.hs:95:0: error:
     error: missing binary operator before token "("
       95 | #if MIN_VERSION_ghc(8,10,0)
          | 
   |
95 | #if MIN_VERSION_ghc(8,10,0)
   | ^

/home/cactus/prog/clash/bugs/clash-issue-1686/Setup.hs:1:1: error:
    `gcc' failed in phase `C pre-processor'. (Exit code: 1)
  |
1 | {-# LANGUAGE CPP, GADTs, RankNTypes, FlexibleContexts #-}
  | ^
```

**Comment by christiaanb** [comment]
Huh? It works for me. What version of `stack` are you using? I'm using:
```
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
```

**Comment by gergoerdi** [comment]
Same Stack version. It looks like I need to add `ghc` as a custom-setup dependency in `package.yaml`.

**Comment by christiaanb** [comment]
Ah, oops. I guess I missed that in the PR.

**Comment by gergoerdi** [comment]
OK, I'm trying to port this to the real Clashilator, but it seems the `Manifest` type must have changed a bit in the meantime:     

> • Variable not in scope: `portInTypes` :: `[Text]`

**Comment by christiaanb** [comment]
It seems we dropped them in https://github.com/clash-lang/clash-compiler/commit/4765591f72a8ed215acd92ebb11cdb5915ed4024#diff-835ff819fc3f3eedaece0bf06aee536eaa5b483a4fb3515849aeb53dcbb43b70 since we stopped using them internally. But for external use it's probably worthwhile to keep them. Hopefully @martijnbastiaan can elaborate?

**Comment by martijnbastiaan** [comment]
Ooh I actually looked into `clashilator` when making this change, but I overlooked the part where it used `portInTypes`. I'll restore them.

**Pull request merged**
